name: Update report

# on:
#   schedule:
#     - cron: '55 23 * * *'
on:
  push:
    branches:
      - 'master'

jobs:
  build_and_run:
    name: Sync & generate
    runs-on: ubuntu-latest
    env:
      RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
      CI_COMMIT_AUTHOR: "Continuous Integration"
      CI_COMMIT_MESSAGE: "update"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CD_GIT_TOKEN }}

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: Grab collection
        run: |
          unset RCLONE_CONFIG
          unset RCLONE_CONF
          rclone copy lp-lucaperic:User\ 1/collection.anki2 .

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Generate report
        run: |
          ./ci_build.sh
          uv run get_report.py

      - name: Commit report
        run: |
          echo "Ran by ${GITHUB_ACTOR}..."
          git_diff_output=$(git diff)
          if [ -z "$git_diff_output" ]; then
            echo "Statefile wasn't updated after all..."
          else
            git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
            git config --global user.email "username@users.noreply.github.com"
            git add report.html
            git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
            git push
          fi
